[[main]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/KubeMite/wiki"
  weight = 1

[[main]]
  name = "About"
  pageRef = "about"
  weight = 2

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 3

[[main]]
  name = "Subjects"
  weight = 4

[[main]]
  name = "Kubernetes"
  parent = "Subjects"
  pageRef = "kubernetes/"

[[main]]
  name = "Helm"
  parent = "Subjects"
  pageRef = "helm/"

[[main]]
  name = "Gitlab-CI"
  parent = "Subjects"
  pageRef = "gitlab-ci/"

[[main]]
  name = "Homelab"
  parent = "Subjects"
  pageRef = "homelab/"

[[main]]
  name = "K3S"
  parent = "Subjects"
  pageRef = "k3s/"

[[main]]
  name = "Laptop Setup"
  parent = "Subjects"
  pageRef = "laptop-setup/"

[[main]]
  name = "Docker"
  parent = "Subjects"
  pageRef = "docker/"

[[main]]
  name = "Matlab"
  parent = "Subjects"
  pageRef = "matlab/"

[[main]]
  name = "Github Actions"
  parent = "Subjects"
  pageRef = "github-actions/"