name: CI Tests

on:
  workflow_call:

jobs:

  test-hugo:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
        with:
          hugo-version: '0.157.0'
          extended: true

      - name: Test site build
        run: |
          cd docker
          hugo --minify

  test-dockerfile:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          dockerfile: ./docker/Dockerfile
          failure-threshold: warning
