name: CI Tests

on:
  workflow_call:

jobs:

  test-hugo:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
        with:
          hugo-version: '0.157.0'
          extended: true

      - name: Test site build
        run: hugo --minify

  test-dockerfile:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          dockerfile: Dockerfile
          failure-threshold: warning

  test-docker-image:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Build Docker Image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 #v7.0.0
        with:
          platforms: linux/amd64
          load: true
          tags: local/docker-image
          push: false
          sbom: false
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 #v0.35.0
        with:
          image-ref: local/docker-image
          format: sarif
          output: trivy-results.sarif

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@7434149006143a4d75b82a2f411ef15b03ccc2d7 #v4.35.1
        if: always()
        with:
          sarif_file: trivy-results.sarif

  website-security-testing:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Build Docker Image
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 #v7.0.0
        with:
          platforms: linux/amd64
          load: true
          tags: local/docker-image
          push: false
          sbom: false
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run website
        run: |
          docker run -p 8080:80 --name website -d local/docker-image
          timeout 60s bash -c 'until curl -sS -f http://localhost:8080; do sleep 2; done'

      - name: ZAP Scan
        uses: zaproxy/action-baseline@de8ad967d3548d44ef623df22cf95c3b0baf8b25 #v0.15.0
        id: zap-scan
        with:
          target: http://localhost:8080
          token: ${{ secrets.GITHUB_TOKEN }}
          rules_file_name: ./.github/workflows/.zap/rules.tsv
          fail_action: true

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: steps.zap-scan.outcome == 'success'
        with:
          name: zap_scan
          path: |
            report_json.json
            report_html.html
            report_md.md
