name: Pull Request to main

on:
  pull_request:
    branches:
      - main

jobs:

  run-tests:
    uses: ./.github/workflows/_tests.yaml

  dry-build-dockerfile:
    runs-on: ubuntu-22.04
    needs: run-tests

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build
        uses: docker/build-push-action@v7
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          sbom: true
          cache-from: type=gha
          cache-to: type=gha,mode=max